#server:
#  port: 8080

spring:
  application:
    name: clothing-store

#  datasource:
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}}/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}

#  datasource:
#    url: jdbc:mysql://localhost:3306/clothing_store_db
#    username: root
#    password: 55712202
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

# noinspection undefined
sliders.dir: src/main/resources/static/images/sliders/

# noinspection undefined
story.dir: src/main/resources/static/images/story/

# noinspection undefined
highlight.dir: src/main/resources/static/images/highlight/

# noinspection undefined
categorical-sliders.dir: src/main/resources/static/images/categorical-sliders/

